#!/bin/sh
########################################################################
# Begin nfs-client
#
# Description : Start statd
#
# Authors     : Ken Moffat - ken@linuxfromscratch.org
#               Bruce Dubbs - bdubbs@linuxfromscratch.org
#
# Version     : LFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:          iptables
# Required-Start:    
# Should-Start:
# Required-Stop:     $local_fs
# Should-Stop:
# Default-Start:     3 4 5
# Default-Stop:     
# Short-Description: Starts statd
# Description:       rpc.statd provides file locking on nfs.
# X-LFS-Provided-By: BLFS / LFS 7.0
### END INIT INFO

. /lib/lsb/init-functions

#$LastChangedBy: bdubbs $
#$Date: 2011-12-06 23:38:54 +0000 (Tue, 06 Dec 2011) $

case "$1" in
    start)
        if [ -x /etc/init.d/ip6tables ]; then
          log_info_msg "Starting ip6tables..."
          /usr/sbin/ip6tables-restore /etc/sysconfig/ip6tables
          evaluate_retval
        fi
        ;;

    lock)
        log_info_msg "Locking system iptables firewall..."
        /usr/sbin/ip6tables --policy INPUT   DROP
        /usr/sbin/ip6tables --policy OUTPUT  DROP
        /usr/sbin/ip6tables --policy FORWARD DROP
        /usr/sbin/ip6tables           --flush
        /usr/sbin/ip6tables           --delete-chain
        /usr/sbin/ip6tables -A INPUT  -i lo -j ACCEPT
        /usr/sbin/ip6tables -A OUTPUT -o lo -j ACCEPT
        evaluate_retval
        ;;

    clear)
        log_info_msg "Clearing system iptables iptables..."
        /usr/sbin/ip6tables --policy INPUT   ACCEPT
        /usr/sbin/ip6tables --policy OUTPUT  ACCEPT
        /usr/sbin/ip6tables --policy FORWARD ACCEPT
        /usr/sbin/ip6tables           --flush
        /usr/sbin/ip6tables           --delete-chain
        /usrevaluate_retval
        ;;

    status)
        /usr/sbin/ip6tables           --numeric --list
        ;;

    *)
        echo "Usage: $0 {start|clear|lock|status}"
        exit 1
        ;;
esac

# End /etc/init.d/ip6tables
