#!/bin/sh
########################################################################
# Begin ntpd
#
# Description : Copy rw mode files to virtual fs
#
# Author      : DJ Lucas - dj@linuxfromscratch.org
#               Bruce Dubbs - bdubbs@linuxfromscratch.org
#
# Version     : LFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:            local_rw
# Required-Start:      $time $network
# Should-Start:        $remote_fs
# Required-Stop:       $network
# Should-Stop:         $remote_fs
# Default-Start:       3 4 5
# Default-Stop:        0 1 2 6
# Short-Description:   Local_rw
# Description:         Copy rw mode files to virtual fs
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
   start)
      log_info_msg "Copying rw files to virtfs..."
      cp -rf /rw_static/* /local_rw/
      chmod 777 /local_rw/home
      chown -R 500 /local_rw/home/netops
      chgrp -R 500 /local_rw/home/netops
      evaluate_retval
      ;;

   *)
      echo "Usage: $0 {start}"
      exit 1
      ;;
esac

# End ntpd

