#!/bin/sh
########################################################################
# Begin udev
#
# Description : Udev cold-plugging script
#
# Authors     : Zack Winkles, Alexander E. Patrakov
#               DJ Lucas - dj@linuxfromscratch.org
# Update      : Bruce Dubbs - bdubbs@linuxfromscratch.org
#
# Version     : LFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:            udev
# Required-Start:
# Should-Start:        modules
# Required-Stop:
# Should-Stop:
# Default-Start:       S
# Default-Stop:
# Short-Description:   Populates /dev with device nodes.
# Description:         Mounts a tempfs on /dev and starts the udevd daemon.
#                      Device nodes are created as defined by udev.
# X-LFS-Provided-By:   LFS
### END INIT INFO


case "${1}" in
   start)
      if ! grep -q '[[:space:]]sysfs' /proc/mounts; then
         echo "FAILURE:\n\nUnable to create "
         echo "${msg}devices without a SysFS filesystem\n\n"
         echo "${msg}After you press Enter, this system "
         echo "${msg}will be halted and powered off.\n\n"
         /etc/rc.d/init.d/halt stop
      fi
      
      # Mount a temporary file system over /dev, so that any devices
      # made or removed during this boot don't affect the next one.
      # The reason we don't write to mtab is because we don't ever
      # want /dev to be unavailable (such as by `umount -a').
      if ! mountpoint /dev > /dev/null; then
         mount -n -t tmpfs tmpfs /dev -o mode=755
      fi
	
      if [ ${?} != 0 ]; then
         echo "FAILURE:\n\nCannot mount a tmpfs "
         echo "${msg}onto /dev, this system will be halted.\n\n"
         echo "${msg}After you press Enter, this system "
         echo "${msg}will be halted and powered off.\n\n"
         /etc/rc.d/init.d/halt stop
      fi

#      mknod -m 666 /dev/null c 1 3	
      mkdir /dev/pts 
      mount /dev/pts
      ln -s /run/shm /dev/shm
	
      # Udev handles uevents itself, so we don't need to have
      # the kernel call out to any binary in response to them
      echo > /proc/sys/kernel/hotplug

      # Start the udev daemon to continually watch for, and act on,
      # uevents
      /sbin/udevd --daemon

      # Now traverse /sys in order to "coldplug" devices that have
      # already been discovered
	
      /sbin/udevadm trigger --action=add --type=subsystems
      /sbin/udevadm trigger --action=add --type=devices

      # Now wait for udevd to process the uevents we triggered
      /sbin/udevadm settle
      ;;

   *)
      echo "Usage ${0} {start}"
      exit 1
      ;;
esac

exit 0

# End udev
